apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Resources
metadata:
  name: cis-resources
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
      - StatefulSet
      - DaemonSet
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters: {}
