apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Requiredlabels
metadata:
  name: cis-requiredlabels
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    excludedNamespaces:
    - argocd
    - kube-system
    - gatekeeper-system
  parameters: {}
