apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: cake-require-labels
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: ["*"]
        kinds: ["Deployment", "StatefulSet"]
  parameters:
    labels: ["team", "org"]
    labelValues:
      team:
        - "kltn"
      org:
        - "kltn"
