apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoHostpathVolumes
metadata:
  name: cis-hostpath-volumes
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters:
    volumes:
    - hostPath
