apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImageAllowlistWithExemption
metadata:
  name: cis-exempt-namespace
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
    - kube-system
    - kube-public
    - kube-node-lease
    - gatekeeper-system
    - argocd
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
      - StatefulSet
  parameters:
    allowedImages:
    - allowed.registry.com/
