apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedImages
metadata:
  name: cis-allowed-images
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
    - argocd
    - gatekeeper-system
    - kube-system
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
  parameters:
    exempt_image_namespaces:
    - devlake
