apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AllowedImages
metadata:
  name: cis-image-allowed-images
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    excludedNamespaces:
    - argocd
    - config-management-system
    - default
    - devlake
    - gatekeeper-system
    - kube-node-lease
    - kube-public
    - kube-system
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
  parameters:
    allowed_images:
    - '*'
