apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DenyNamespaceDefault
metadata:
  name: denynamespacedefault
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    exemptImages:
    - nginx:1.25.0
