apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoHostpath
metadata:
  name: nohostpath
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    excludedNamespaces:
    - gatekeeper-system
    - kube-system
  parameters: {}
