apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoInternetTraffic
metadata:
  name: no-internet-traffic
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - NetworkPolicy
    - apiGroups:
      - ''
      kinds:
      - Service
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters:
    internet_cidr: 0.0.0.0/0
