apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoPrivilegedContainers
metadata:
  name: no-privileged-containers
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  match:
    kinds:
    - apiGroups:
      - ''
      - apps
      kinds:
      - Pod
      - Deployment
      - StatefulSet
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
  parameters:
    allowPrivileged: false
