apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoRootContainers
metadata:
  name: norootcontainers
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
      - StatefulSet
      - DaemonSet
      - ReplicaSet
    - apiGroups:
      - batch
      kinds:
      - Job
      - CronJob
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
  parameters:
    exemptImages:
    - alpine:3.18
