apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoRootPods
metadata:
  name: no-root-pods
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters: {}
