apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoSecretsAsEnv
metadata:
  name: no-secrets-as-env
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
      - StatefulSet
      - DaemonSet
    - apiGroups:
      - batch
      kinds:
      - Job
      - CronJob
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
    - kong
  parameters: {}
