apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireResource
metadata:
  name: requireresource
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: deny
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    namespaces:
      exclude:
      - kube-system
      - gatekeeper-system
  parameters: {}
