apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireLabels
metadata:
  name: requirelabels
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  enforcementAction: deny
  match:
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
      - StatefulSet
      - DaemonSet
      - ReplicaSet
    - apiGroups:
      - batch
      kinds:
      - Job
  parameters:
    requiredLabels:
    - team
    - org
