apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireResource
metadata:
  name: require-resource
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: deny
  match:
    kinds:
    - Pod
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
  parameters: {}
