apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictCapabilities
metadata:
  name: restrictcapabilities
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  metadata:
    name: restrictcapabilities
  spec:
    enforcementAction: deny
    match:
      kinds:
      - apiGroups:
        - ''
        kinds:
        - Pod
      - apiGroups:
        - apps
        kinds:
        - Deployment
        - StatefulSet
      excludedNamespaces:
      - kube-system
      - gatekeeper-system
    parameters: {}
