apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictCapabilities
metadata:
  name: restrictcapabilities
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  parameters:
    exemptImages:
    - nginx:1.24.0
