apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: banishnamespacedefault
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: BanishNamespaceDefault
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package bannspacedefault

      violation[{"msg": msg}] {
        namespace := input.review.object.metadata.namespace
        namespace == "default"
        msg := sprintf("Namespace '%v' is not allowed", [namespace])
      }
