apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: hostpathvolume
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: HostpathVolume
      validation:
        openAPIV3Schema:
          type: object
          properties:
            disallowHostPath:
              type: boolean
          required:
          - disallowHostPath
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package hostpathvolume

      violation[{"msg": msg, "details": {"volume": vol.name}}] {
          object.get(input.parameters, "disallowHostPath", false)
          vol := get_volume()
          vol.hostPath
          msg := sprintf("hostPath volume %q is not allowed", [vol.name])
      }

      get_volume := vol {
          input.review.object.kind == "Pod"
          vol := input.review.object.spec.volumes[_]
      }
      get_volume := vol {
          input.review.object.kind != "Pod"
          vol := input.review.object.spec.template.spec.volumes[_]
      }
