apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: nohostpathvolume
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: NoHostpathVolume
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package nohostpathvolume

      violation[{"msg": msg}] {
        is_workload
        volume := input.review.object.spec.template.spec.volumes[_]
        hostPath := object.get(volume, "hostPath", null)
        hostPath != null
        msg := sprintf("HostPath volume %v is not allowed", [volume.name])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Pod"
        volume := input.review.object.spec.volumes[_]
        hostPath := object.get(volume, "hostPath", null)
        hostPath != null
        msg := sprintf("HostPath volume %v is not allowed", [volume.name])
      }

      is_workload {
        kinds := {"Deployment", "StatefulSet", "DaemonSet", "ReplicaSet", "Job"}
        kinds[input.review.kind.kind]
      }
