apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: nohostports
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: NoHostports
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package nohostports

      violation[{\
