apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: no-internet-traffic
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: NoInternetTraffic
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: "package nointernettraffic\n\nviolation[{\"msg\": msg}] {\n  not isExemptNamespace(input.metadata.namespace)\n\
      \  resource := input.kind.kind\n  spec := object.get(input.spec, \"template\"\
      , input.spec) # Handle Jobs and CronJobs\n  containers := object.get(spec, \"\
      containers\", [])\n  initContainers := object.get(spec, \"initContainers\",\
      \ [])\n  ephemeralContainers := object.get(spec, \"ephemeralContainers\", [])\n\
      \n  container := array.concat(containers, array.concat(initContainers, ephemeralContainers))[idx]\n\
      \  securityContext := object.get(container, \"securityContext\", {})\n\n  #\
      \ Check container image name for internet access\n  image := container.image\n\
      \  startswith(image, \"docker.io/\")\n  msg := sprintf(\"Container '%v' in %v\
      \ '%v' uses image '%v' from docker.io which may be publicly accessible.  Ensure\
      \ the image is from a trusted and controlled registry.\", [container.name, resource,\
      \ input.metadata.name, image])\n}\n\nviolation[{\"msg\": msg}] {\n  not isExemptNamespace(input.metadata.namespace)\n\
      \  resource := input.kind.kind\n  spec := object.get(input.spec, \"template\"\
      , input.spec) # Handle Jobs and CronJobs\n  containers := object.get(spec, \"\
      containers\", [])\n  initContainers := object.get(spec, \"initContainers\",\
      \ [])\n  ephemeralContainers := object.get(spec, \"ephemeralContainers\", [])\n\
      \n  container := array.concat(containers, array.concat(initContainers, ephemeralContainers))[idx]\n\
      \  securityContext := object.get(container, \"securityContext\", {})\n\n  #\
      \ Check container for hostNetwork = true\n  container.securityContext.hostNetwork\
      \ == true\n  msg := sprintf(\"Container '%v' in %v '%v' uses hostNetwork=true\
      \ which allows direct access to the host's network and may bypass network policies.\
      \  Set hostNetwork to false.\", [container.name, resource, input.metadata.name])\n\
      }\n\nviolation[{\"msg\": msg}] {\n  not isExemptNamespace(input.metadata.namespace)\n\
      \  resource := input.kind.kind\n  spec := object.get(input.spec, \"template\"\
      , input.spec) # Handle Jobs and CronJobs\n\n  spec.hostNetwork == true\n  msg\
      \ := sprintf(\"%v '%v' uses hostNetwork=true which allows direct access to the\
      \ host's network and may bypass network policies.  Set hostNetwork to false.\"\
      , [resource, input.metadata.name])\n}\n\nisExemptNamespace(ns) {\n  ns == \"\
      kube-system\"\n}\n\nisExemptNamespace(ns) {\n  ns == \"gatekeeper-system\"\n\
      }\n\nisExemptNamespace(ns) {\n  ns == \"argocd\"\n}\n"
