apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: no-internet-access
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: NoInternetAccess
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package nointernetaccess

      violation[{"msg": msg}] {
        not_allowed_egress := object.get(input.object.spec, "egress", [])
        count(not_allowed_egress) > 0
        msg := sprintf("Internet egress is not allowed, but found egress rules: %v", [not_allowed_egress])
      }

      violation[{"msg": msg}] {
        spec := input.object.spec
        has_host_network := object.get(spec, "hostNetwork", false)
        has_host_network
        msg := "Internet egress is not allowed, hostNetwork should not be enabled"
      }
