apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requireresource
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: RequireResource
      validation:
        openAPIV3Schema:
          type: object
          properties:
            requiredResources:
              type: array
              items:
                type: string
              description: List of required resource names (e.g., cpu, memory).
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package requireresource

      violation[{"msg": msg}] {
        is_workload
        not exempt_namespace
        container := input.review.object.spec.template.spec.containers[_]
        missing_resource(container)
        msg := sprintf("Container '%v' is missing required resource requests.", [container.name])
      }

      violation[{"msg": msg}] {
        input.review.kind.kind == "Pod"
        not exempt_namespace
        container := input.review.object.spec.containers[_]
        missing_resource(container)
        msg := sprintf("Container '%v' is missing required resource requests.", [container.name])
      }

      missing_resource(container) {
        required_resources := {r | r := input.parameters.requiredResources[_]}
        provided_resources := {r | r := container.resources.requests; contains(required_resources, r)}
        count(required_resources - provided_resources) > 0
      }

      is_workload {
        kinds := {"Deployment", "StatefulSet", "DaemonSet"}
        kinds[input.review.kind.kind]
      }

      exempt_namespace {
        input.review.namespace == "kube-system"
      }

      exempt_namespace {
        input.review.namespace == "gatekeeper-system"
      }

      exempt_namespace {
        input.review.namespace == "kubecheck"
      }
