apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requireresource
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: RequireResource
      validation:
        openAPIV3Schema:
          type: object
          properties:
            requiredResources:
              type: array
              items:
                type: string
              description: List of resource names that must be requested by each container
            exemptImages:
              type: array
              items:
                type: string
              description: Parameter exemptImages for policy.
          required:
          - requiredResources
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package requireresource

      violation[{"msg": msg}] {
        # Determine the container list based on the resource kind
        containers := get_containers(input.review)

        # Skip exempted images
        exemptImages := object.get(input.parameters, "exemptImages", [])
        container := containers[_]
        image := object.get(container, "image", "")
        not contains(exemptImages, image)

        # Check required resources
        resources := object.get(container, "resources", {})
        requests := object.get(resources, "requests", {})
        provided := {resource_type | requests[resource_type]}
        required := {resource_type | resource_type := input.parameters.requiredResources[_]}
        missing := required - provided
        count(missing) > 0
        msg := sprintf("container %v does not have %v requests defined", [container.name, missing])
      }

      # Helper to get containers for different kinds
      get_containers(review) = containers {
        review.kind.kind == "Pod"
        containers := review.object.spec.containers
      }
      get_containers(review) = containers {
        review.kind.kind == "Deployment"
        containers := review.object.spec.template.spec.containers
      }
      get_containers(review) = containers {
        review.kind.kind == "StatefulSet"
        containers := review.object.spec.template.spec.containers
      }
