apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: requireresource
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: RequireResource
      validation:
        openAPIV3Schema:
          type: object
          properties: {}
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package requireresource

      violation[{
        "msg": msg,
        "details": {"container": container.name}
      }] {
        input.review.object.kind == "Pod"
        container := input.review.object.spec.containers[_]
        not container.resources.requests.cpu
        msg := sprintf("Container %s has no CPU request", [container.name])
      }

      violation[{
        "msg": msg,
        "details": {"container": container.name}
      }] {
        input.review.object.kind == "Pod"
        container := input.review.object.spec.containers[_]
        not container.resources.requests.memory
        msg := sprintf("Container %s has no memory request", [container.name])
      }

      violation[{
        "msg": msg,
        "details": {"container": container.name}
      }] {
        input.review.object.kind == "Pod"
        container := input.review.object.spec.containers[_]
        not container.resources.limits.cpu
        msg := sprintf("Container %s has no CPU limit", [container.name])
      }

      violation[{
        "msg": msg,
        "details": {"container": container.name}
      }] {
        input.review.object.kind == "Pod"
        container := input.review.object.spec.containers[_]
        not container.resources.limits.memory
        msg := sprintf("Container %s has no memory limit", [container.name])
      }
