apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: restrictcapabilities
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: RestrictCapabilities
      validation:
        openAPIV3Schema:
          openAPIV3Schema:
            type: object
            properties:
              exemptImages:
                type: array
                items:
                  type: string
                description: List of container images that are exempt from capability
                  restrictions.
            required:
            - exemptImages
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: "package restrictcapabilities\n\n# Helper to check if a container image\
      \ is exempt\nis_exempt_image(container) {\n  image := container.image\n  exempt_images\
      \ := input.parameters.exemptImages\n  count([img | img := exempt_images[_];\
      \ endswith(image, img)]) > 0\n}\n\n# Deny rule: if the pod contains a container\
      \ that is not exempt and has any capabilities\nviolation[reason] {\n  pod :=\
      \ input.review.object\n  pod.kind == \"Pod\"\n  container := pod.spec.containers[_]\n\
      \  not is_exempt_image(container)\n  # Example capability check \u2013 replace\
      \ with actual capability logic\n  container.securityContext.capabilities !=\
      \ null\n  reason := sprintf(\"Container %s in pod %s/%s is not exempt and has\
      \ capabilities\", [container.name, pod.metadata.namespace, pod.metadata.name])\n\
      }\n"
