apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: restrict-capabilities
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: RestrictCapabilities
      validation:
        openAPIV3Schema:
          type: object
          properties:
            allowedCapabilities:
              type: array
              items:
                type: string
              description: List of allowed capabilities. Defaults to ["NET_BIND_SERVICE"]
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package restrictcapabilities

      violation[{"msg": msg, "details": {}}] {
        container := input.review.object.spec.containers[_]
        not allowed_capabilities(container)
        msg := sprintf("Container '%v' has forbidden capabilities.", [container.name])
      }

      violation[{"msg": msg, "details": {}}] {
        container := input.review.object.spec.initContainers[_]
        not allowed_capabilities(container)
        msg := sprintf("Init Container '%v' has forbidden capabilities.", [container.name])
      }

      violation[{"msg": msg, "details": {}}] {
        container := input.review.object.spec.ephemeralContainers[_]
        not allowed_capabilities(container)
        msg := sprintf("Ephemeral Container '%v' has forbidden capabilities.", [container.name])
      }

      allowed_capabilities(container) {
        securityContext := object.get(container, "securityContext", {})
        capabilities := object.get(securityContext, "capabilities", {})
        drop := object.get(capabilities, "drop", [])
        contains(drop, "ALL")
      }

      allowed_capabilities(container) {
        securityContext := object.get(container, "securityContext", {})
        capabilities := object.get(securityContext, "capabilities", {})
        drop := object.get(capabilities, "drop", [])
        allowedCapabilities := object.get(input.parameters, "allowedCapabilities", ["NET_BIND_SERVICE"])
        count(array.diff(allowedCapabilities, drop)) == count(allowedCapabilities)
      }
