apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: seccompdefault
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  crd:
    spec:
      names:
        kind: SeccompDefault
      validation:
        openAPIV3Schema:
          openAPIV3Schema:
            type: object
            properties:
              seccompProfile:
                type: string
                enum:
                - RuntimeDefault
                - Localhost
                - Unconfined
            required:
            - seccompProfile
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package seccompdefault

      violation[{"msg": msg}] {
          kind := input.review.object.kind
          containers := get_containers(kind, input.review.object)
          container := containers[_]
          seccomp := object.get(container.securityContext, "seccompProfile", {})
          type := object.get(seccomp, "type", "")
          type != input.parameters.seccompProfile
          msg := sprintf("Container %s has seccompProfile %s, expected %s", [container.name, type, input.parameters.seccompProfile])
      }

      get_containers("Pod", obj) = obj.spec.containers
      get_containers(_, obj) = obj.spec.template.spec.containers
