apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoRootContainers
metadata:
  name: no-root-containers
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters:
    exemptImages:
    - nginx:latest
