apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RestrictAutomountserviceaccounttoken
metadata:
  name: restrict-automountserviceaccounttoken
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  enforcementAction: dryrun
  match:
    kinds:
    - apiGroups:
      - ''
      kinds:
      - Pod
    - apiGroups:
      - apps
      kinds:
      - Deployment
    - apiGroups:
      - apps
      kinds:
      - StatefulSet
    - apiGroups:
      - apps
      kinds:
      - DaemonSet
    - apiGroups:
      - batch
      kinds:
      - Job
    - apiGroups:
      - batch
      kinds:
      - CronJob
    excludedNamespaces:
    - kube-system
    - gatekeeper-system
    - argocd
  parameters: {}
